# This file will be included by the Makefile under the project directory.

FLOAT_O := $(FLOAT:.a=.o)
FLOAT_VFPRINTF_O := $(dir $(FLOAT))FLOAT_vfprintf.o

FLOAT_A_OBJ := $(FLOAT_O) $(FLOAT_VFPRINTF_O)

$(FLOAT): $(FLOAT_A_OBJ)
	ar r $@ $^

$(FLOAT_O):$(LIB_COMMON_DIR)/FLOAT/FLOAT.c 
	$(call make_command, $(CC), $(FLOAT_CFLAGS), cc $@, $^)

$(FLOAT_VFPRINTF_O):$(LIB_COMMON_DIR)/FLOAT/FLOAT.c 
	$(call make_command, $(CC), $(FLOAT_CFLAGS), cc $@, $^)

